### ISSUE TITLE
Implementation of Clipping Representation

### ISSUE THREAD

**Issue by agviegas** [agviegas/IFC.js#12]
IFC can generate geometries in various forms. One of them is Clipping Operations, ergo, boolean operations. Generally, the only boolean operation included in IFC is _difference_. A common case for this are the walls that are cut by slabs. In this case, the wall is represented as a whole wall, and then the subtraction is applied. The tasks for this issue are:

- [x] Understanding how clipping is expressed in IFC.
- [x] Understanding how clipping could be applied in Three.js. This is already implemented for extracting the OpeningElements from the walls geometry by _difference_ boolean operations. See file [boolean-operator.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-operator/boolean-operator.js).

- [x] Adding the logic to [ifc-clipping.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/ifc-clipping.js) to extract the necessary information.
- [x] Adding the logic to [three-clipping.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/three-clipping.js) file that takes this information and generates the geometry.
- [x] Testing different use cases.

The testing files provided for this issue can be found [here](https://drive.google.com/drive/folders/1eAh5QUMgx-jDsLN6GmKLXFelKjTVzYEB?usp=sharing).

**Comment by agviegas** [comment]
Some context about this topic: <br>
`Clipping Representation` is the representation based exclusively on the use of boolean results of clipped solids, so that:
- The first operand is either a solid or the result of another operation.
- The second operand is always a `half space solid` 
- The operation performed is always _Difference_. 

The commonest use case for this kind of representation are `IfcWall` instances. The wall `body` can be cut out (clipped) at the bottom or top (e.g. for walls in rooms with sloped ceilings). The only restriction is that the cutting element has to be a plane. The following picture shows examples of valid clipped walls.

![image](https://user-images.githubusercontent.com/56475338/102025677-eb2fc880-3d99-11eb-811e-80aa549e49ee.png)

The following conditions are fullfilled in any IFC: 

- Only the top or bottom faces may be cut. That is, cutting the side faces (start cap and end cap) can't be expressed using this kind of representation. This is managed using `IfcArbitraryProfileDef` and `IfcRelConnectsPathElement` instances. 
- No cuts may be made parallel or tangent to the wall path.
- No cuts may be used to open holes in the wall: this is handled with `IfcOpeningElement` instances.

Finally, there are two types of cutting planes: unlimited and bounded. 
- For unlimited cutting planes (unbounded clipping plans) both `IfcHalfSpaceSolid` and `IfcBoxedHalfSpace` can be used. 
- For bounded clipping planes only `IfcPolygonalBoundedHalfSpace` can be used.

Below you can see a simple example of a wall with this representation:

![image](https://user-images.githubusercontent.com/56475338/102025999-d18f8080-3d9b-11eb-8375-72f3766a94df.png)


```javascript
 #1=IFCWALLSTANDARDCASE('abcdefghijklmnopqrst01', #2, $, $, $, #3, #4, $);
#3=IFCLOCALPLACEMENT($, #10);
#4=IFCPRODUCTDEFINITIONSHAPE($, $, (#11, #13));
#10=IFCAXIS2PLACEMENT3D(#16, $, $);
#16=IFCCARTESIANPOINT((2.0E+00, 1.0E+00, 0.0E+00));
#12=IFCGEOMETRICREPRESENTATIONCONTEXT($, $, 3, $, #14, $);
#14=IFCAXIS2PLACEMENT3D(#15, $, $);
#15=IFCCARTESIANPOINT((0.0E+00, 0.0E+00, 0.0E+00));
/* shape representation of the wall axis */
#11=IFCSHAPEREPRESENTATION(#12, 'Axis', 'Curve2D', (#18));
#18=IFCTRIMMEDCURVE(#19,(#20),(#21),.T.,.CARTESIAN.);
#19=IFCLINE(#30, #31);
#30=IFCCARTESIANPOINT((0.0E+00, 0.0E+00));
#31=IFCVECTOR(#32,2.8E+00);
#32=IFCDIRECTION((1.0E+00, 0.0E+00));
#20=IFCCARTESIANPOINT((0.0E+00, 0.0E+00));
#21=IFCCARTESIANPOINT((2.80E+00, 0.0E+00));
/* shape representation of the clipped body */
#13=IFCSHAPEREPRESENTATION(#12, 'Body', 'Clipping', (#50));
#50=IFCBOOLEANCLIPPINGRESULT(.DIFFERENCE., #22, #51);
/* geometric representation of the extruded solid */
#22=IFCEXTRUDEDAREASOLID(#23, #26, #29, 2.80E+00);
#26=IFCAXIS2PLACEMENT3D(#28, $, $);
#28=IFCCARTESIANPOINT((0.0E+00, 0.0E+00, 0.0E+00));
#29=IFCDIRECTION((0.0E+00, 0.0E+00, 1.0E+00));
#23=IFCARBITRARYCLOSEDPROFILEDEF(.AREA., $, #40);
#40=IFCPOLYLINE((#41,#42,#43,#44,#41));
#41=IFCCARTESIANPOINT((0.0E+00, 1.0E-01));
#42=IFCCARTESIANPOINT((2.8E+00, 1.0E-01));
#43=IFCCARTESIANPOINT((2.8E+00, -1.0E-01));
#44=IFCCARTESIANPOINT((0.0E+00, -1.0E-01));
/* geometric representation of the clipping plane */
#51=IFCHALFSPACESOLID(#52, .F.);
#52=IFCPLANE(#53);
#53=IFCAXIS2PLACEMENT3D(#54, #55, #56);
#54=IFCCARTESIANPOINT((0.0E+00, 0.0E+00, 2.0E+00));
#55=IFCDIRECTION((0.0E+00, -0.7070106E+00, 0.7070106E+00));
#56=IFCDIRECTION((1.0E+00, 0.0E+00, 0.0E+00));
```

**Comment by apemann** [comment]
Here are some notes from what I've learned so far:

- As described in the paper by [Zhu _et al_](https://www.mdpi.com/2076-3417/10/6/2009), for this to work you need to convert any unbounded half space solids into a finite volume (in their case a BRep, in our case a CSG mesh). 
- This requires making some assumptions in order to define the missing limits/boundaries that define the solid. The values suggested in the paper are 100 x 100 m in the x-y plane and 20 m in the z-plane. This is to ensure that the volume has a high enough probability of covering the main body to be clipped.
- This will likely require fine tuning however, and it seems to have caused issues with the IfcOpenShell project e.g. [here](https://github.com/IfcOpenShell/IfcOpenShell/issues/185) and [here](https://github.com/IfcOpenShell/IfcOpenShell/issues/6).
- Another problem to work around is that there is no consistent ordering in IFC files for the items in a given clipping cascade. A clipping cascade is where you have more than one clipping operation performed on an object, where the first operand is a reference to the next clipping result. In this case an IFCBOOLEANCLIPPINGRESULT item is created for each operation, and these need to be processed in sequence. However then you first encounter a clipping result while iterating over the items, you don't know where you are in the cascade (unless the first operand is a solid) or how long the cascade is.

@agviegas let me know if this sounds sensible. I'm going to start working on a solution based on these criteria.

**Comment by agviegas** [comment]
Everything sounds good to me. I have implemented the basic structure for this; make sure to pull the last changes. <br>
In the [ifc-map.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/geometry-map.js) there is now an entry that will handle any geometry of type `Clipping` to [ifc-clipping.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/ifc-clipping.js), which right know is only logging the geometry that receives. If we followed the structure of the rest of the code, there would be two tasks: 

- Query the necessary information from the geometry in [ifc-clipping.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/ifc-clipping.js). Here I suspect that we need a recursive function that iterates through the clipping cascade, constructing an object that contains all the items and operations in order.
- Handle this information to [three-clipping.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-generator/three-clipping.js), that will encapsulate the THREE logic to generate the geometry.

I have executed the last implementation with the first example of the [examples folder](https://drive.google.com/drive/folders/1eAh5QUMgx-jDsLN6GmKLXFelKjTVzYEB?usp=sharing), which is a wall with two cuts, and this is what is logged in the console:

![Captura](https://user-images.githubusercontent.com/56475338/102096979-9afe4800-3e25-11eb-9b1b-e9bf1c840cb8.JPG)

There are two clipping operations that are made through two `IfcPlane` instances. I think that the sequence of actions is: 
1. All the geometry instances are created.
2. The boolean operations are applied using the same library as [here](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-operator/boolean-operator.js) (this is beeing used for extracting the `IfcOpeningElement` instances from the walls).
3. All the geometry (except for the final boolean result) is deleted.

Also, I would consider the following: 
- You don't have to worry about creating the wall yourself, as this is already implemented. You can simply call `getMappedGeometry`. You can see an example of this for the [mapped representations](https://github.com/agviegas/IFC.js/blob/a134b8d108ae605b6c649fe962976c14c37d1cbe/src/ifc-to-three.js/geometry-generator/ifc-mappedRepresentation.js#L33). This function will create the wall (with no boolean operations) and locate it in it`s correct position in space. 
- I think that the easiest option to create the bounded volumes for clipping is [BoxGeometry](https://threejs.org/docs/#api/en/geometries/BoxGeometry), but maybe there is a better option. 
- You need the `Position` property to define the position of the clipping volumes in space. I have solved this in [local-transform-tracker.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-transformer/local-transform-tracker.js) and [ifc-local-transform-applier.js](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-transformer/local-transform-applier.js). You can see examples of their use in other geometries such as [swept solids](https://github.com/agviegas/IFC.js/blob/master/src/ifc-to-three.js/geometry-transformer/local-transform-applier.js), with the functions  `trackLocalTransform` and  `applyTransformsTo`. Once you have created the clipping volumes (in the center of the scene, which is what THREE.js does by default), these functions will place the object in the correct position. Bear in mind that all objects need to be located in space before you can apply the boolean operations.

**Comment by apemann** [comment]
Thanks, that's very helpful! I'll get started on the implementation.

**Comment by agviegas** [comment]
Great! I am excited to see what you do; this is an important milestone in the project. 

If you find yourself struggling with the implementation, don't hesitate to submit a draft pull request with what you have so I can help. 🙂

**Comment by agviegas** [comment]
Once I push my last changes, this will be solved. There might be cases that are not implemented yet, but I think this is a great first step forward in this field. Maybe we can do this in future Issues / PRs.

By the way, I will be showing this advances in [twitter](https://twitter.com/ViegasGonzalez), in case you want to join / show what you have done here. 🙂 

![image](https://user-images.githubusercontent.com/56475338/102523447-d607b200-4097-11eb-8d2d-5779ebace393.png)
![image](https://user-images.githubusercontent.com/56475338/102523467-dc962980-4097-11eb-91b4-a3b6f247d1d5.png)
![image](https://user-images.githubusercontent.com/56475338/102523616-1404d600-4098-11eb-8dbc-a8eef3ac0a75.png)
