### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by j209** [agviegas/IFC.js#24]
Hi
Thanks for your great works.
What about typescript support?
And using ifc.js with [babylon.js](https://github.com/BabylonJS/Babylon.js)?

**Comment by agviegas** [comment]
Right now we are busy finishing the geometric generation, but both functionalities are in the roadmap. 🙂
In the case of Babylon JS support: the good news is that the IFC.js parser is decoupled from the geometry generator, so all that part of the code could be reused. The same geometric generator should be implemented in Babylon.js.

**Comment by agviegas** [comment]
Hey @j209 we already support typescript. Take a look at [web-ifc-three](https://github.com/tomvandig/web-ifc-three) (we have decentralized things). As this is the library in charge of the API now, I'm closing this issue, but feel free to open a new one there!
