### ISSUE TITLE
cannot load *.ifc file

### ISSUE THREAD

**Issue by spookyfox** [agviegas/IFC.js#3]
While file loading, the function: getRepresentationValue(product) gets invoked, whereas the passed product=34 is. This leads to an issue:
`
Uncaught TypeError: Cannot read property 'value' of undefined
    at getRepresentationValue (geometry-mapper.js:32)
    at getRepresentations (geometry-mapper.js:23)
    at geometry-mapper.js:17
    at Array.forEach (<anonymous>)
    at constructGeometry (geometry-mapper.js:16)
    at buildGeometry (converter.js:6)
    at main (index.js:11)
    at FileReader.reader.onload (ifc-file-reader.js:18) 
`
since the product should not be just a number but:
`
 product[n.geomRepresentations] =
    product[n.representation][t.value][n.representations][t.value];
}
`
Thanks for helping.

**Comment by agviegas** [comment]
Hello @spookyfox and thank you for the first issue of this repo! 

This project  started only a couple of weeks ago, so the app is not able to load IFC files yet. If you want to contribute to this project, feel free to PR. Unfortunately, I haven't had time to release a contribution guide yet, but I plan to have this done in the following weeks as well. 

If you just want to use the loader, stay tuned for future updates. 🙂
