### ISSUE TITLE
Geometry optimization

### ISSUE THREAD

**Issue by agviegas** [agviegas/IFC.js#33]
By "optimization" I am not talking about how fast the scene loads, but to be able to handle scenes with hundreds or thousands of objects with no lag.

Right know, the library is creating all objects in the scene and parenting everything to an Object3D, allowing the users to easily add everything to the scene. Nonetheless, this is not the best approach, as we will be facing really big files. There are some reference about making scenes perform better [here](https://threejsfundamentals.org/). Any ideas regarding this will be helpful.

**Comment by vegarringdal** [comment]
This might be a solution later.
https://evilmartians.com/chronicles/faster-webgl-three-js-3d-graphics-with-offscreencanvas-and-web-workers

Beeing able to read IFC in 1 worker using filesystem access api by streaming the data,  Then send it over to new worker building object. Then main thread making the 3d might be a way.

I really know to little about IFCs.
But if the main object we make has internal references these should probably be replace by ID/keys, and maybe using a Map for key/data. So we can make pure json from it/ store it in database. remote or indexdb..

But like I said, know very little so it might be horrible ideas.

**Comment by agviegas** [comment]
Yes, that link will probably help us. We have a step-by-step guide about that topic [here](https://threejsfundamentals.org/threejs/lessons/threejs-offscreencanvas.html). 

In addition, I would also try to optimize the geometry output of the library without forcing the user to apply a certain architecture / optimization measures on their end (even though we can also give them those optimization measures as boilerplate code in the examples folder). In this case, [this](https://threejsfundamentals.org/threejs/lessons/threejs-optimize-lots-of-objects.html) also looks promising.

And yes, another topic is the serialization of the information to be able to store the scene and load it much faster once it has been processed. It might be better to have this in a separate issues though, to try to solve things one by one. 

In this issue the objective is not loading things fast, but avoiding lag when moving around the scene with little effort from the consumer of the library (ideally, not forcing him to do anything else in their end). We can open a separate issue about reducing loading times as much as possible. Obviously everything is related to each other, but I would like to have tasks / PRs as atomic  as possible.

**Comment by andrewisen** [comment]
I managed to merge the geometries. It uses the same logic from the [Three.js Fundamentals article](https://threejsfundamentals.org/threejs/lessons/threejs-optimize-lots-of-objects.html).
However, I've made some modification to make it work with IFC. 

I still have some stuff to figure out before I can share the example/code.
Anyways, I have documented my thoughts [here](https://bimwhale.gitbook.io/ifc-js/optimization/introduction). 

Cheers 🚀 

https://user-images.githubusercontent.com/31659443/106887709-d7437b80-66e5-11eb-974d-2506200b8a58.mp4

**Comment by agviegas** [comment]
@andrewisen very nice. I guess that one of the problems you may have encountered with this is that some geometries are standard geometries whereas others are buffer geometries. This can be solved really easily (standard geometries are no longer supported by Three.js anyway, everything will be buffer).

So, again, once we finish 1.0. I want to read everything carefully and see how can we integrate this as soon as possible, as it will be compulsory for larger scenes. 

I am polishing the last geometric types; once that has been done, I will commit to Three.js and get hands on with all these promising topics!

**Comment by andrewisen** [comment]
> I guess that one of the problems you may have encountered with this is that some geometries are standard geometries whereas others are buffer geometries.

I might be a problem later. But [this](https://stackoverflow.com/a/18263162/14353202) works fine for now :)

**Comment by andrewisen** [comment]
One of the problems that I had was with my merged mesh. I tried to merge hidden meshes, for example an [IfcSpace](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/ifcproductextension/lexical/ifcspace.htm).
This problem should be fixed by now 🥳 

https://user-images.githubusercontent.com/31659443/107024857-df182400-67a8-11eb-8a3c-a5c3bfe56d4c.mp4

A problem with merged meshes is that you lose the BIM-data. For example, you cannot use the object picker - everything is a single object. I wrote a simple workaround for this and I will, of course, explain it later 🤓 

Also, I added a second feature. When the user picks an object, the rest of the scene becomes transparent. 
Behind the scenes there are now two **merged** objects that are generated.

1. Has the same material as the original `structured` object
2. Has a transparent material

The second **merged** object is used during the object picking. I simply switch between these two **merged** objects.
This approach results in a smooth performance and, in my opinion, improvised user experience.

Of course, you can customise the look to whatever you like. I was simply looking for a way to load two merged objects into the same scene 😄

**Comment by agviegas** [comment]
I would also love to see a draft PR with your implementation with this 🙂 don't be afraid to break anything!

**Comment by andrewisen** [comment]
Yhea, I have a bug with some [edges](https://github.com/andrewisen/IFC.js-web-worker-example/issues/3). I'm unsure what went wrong. 

I will take a look at that bug next weekend. And, I will submit a PR anyways. Maybe someone else can solve this bug 🤞

**Comment by agviegas** [comment]
Don't worry about the edges, as probably I will extract them and make them part of the `example` (outside the library).

**Comment by agviegas** [comment]
Hey, this PR should be moved to [web-ifc-three](https://github.com/tomvandig/web-ifc-three). We already have some ideas about how to make geometry more efficient (for example using [IntancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh)).  As IFC.js is no longer responsible for the Three IfcLoader speed, I'm closing this here. Maybe we can start a conversation about this there!
