### ISSUE TITLE
Loading optimization

### ISSUE THREAD

**Issue by andrewisen** [agviegas/IFC.js#35]
This issue refers to how fast the scenes load. In other words, how fast can we parse an IFC file. Check out https://github.com/agviegas/IFC.js/issues/33 for the related `geometry optimization` issue.

I have implemented web workers to allow for "multithreading". Here's a link to my [fork](https://github.com/andrewisen/IFC.js-web-worker-example). I have documented my thoughts [here](https://bimwhale.gitbook.io/ifc-js/web-worker-example/single-web-worker-example) and [here](https://bimwhale.gitbook.io/ifc-js/developer-guide/step-by-step).

TL;DR:

https://user-images.githubusercontent.com/31659443/106889012-b0864480-66e7-11eb-992d-b5c7cdc58386.mp4

The next step is to figure out how to implement my (or a similar) solution into this project. There are many ways to do this. 

I suggest we/you release the first version of `IFC.js` and THEN implement web worker support.
Yes - performance is an important factor. But, I think it's more important to support the most useful IFC2x3 classes. 

Anyways, that's just my thoughts. I'm open to suggestion and I encourage others to experiment with this as well.

**Comment by agviegas** [comment]
This is wonderful! 😀

Yes, I agree. I will finish the first version, and see how can we integrate this. 

I am sure this is something everyone will be willing to use. Once I finish 1.0, I will read all your documentation carefully so hopefully we can have this integrated as soon as possible. Congratulations for the amazing work!

**Comment by agviegas** [comment]
Hey @andrewisen, I finally found some time to take a look at your documentation. It is super nice! I would love to see this in a Pull Request to see how fast IFC.js becomes. 

As I think they are two separate topics, I would start with web workers, and then (in another PR) implement IndexDB. What do you think? You can simply pull the last changes in the code, submit a draft pull request attached to this issue and I can help you with the problems that arise. 🙂

**Comment by andrewisen** [comment]
Yhea, sounds great. I can do some refactoring to my code. I'm a bit busy with other stuff at the moment.
I can hopefully make a PR next weekend (not this weekend) 😄

**Comment by agviegas** [comment]
Great. Also, beware that if the reason not to use web workers with `buildGeometry` is that it doesn't support THREE.js, I can shift all THREE.js logic forward, so we can hopefully fit as much as we can inside the workers, and only in the end call THREE.js entities. Anyway, let's have a first implementation and see how it looks like!

**Comment by andrewisen** [comment]
I had some extra time to look at my code 🤓 

Firstly, I did some major [code refactoring](https://github.com/andrewisen/IFC.js-web-worker-example/commit/c1570aa48d222eaffedff05c4875027e3b036c8e). I have separated the examples, which will make the PR much nicer. My examples are now placed in the `04` folder, see more [here](https://github.com/andrewisen/IFC.js-web-worker-example/tree/master/examples/04).

I will take a short break (I have other stuff to do atm) and get back to this during this weekend.
I will fix some minor stuff and then submit a PR for each topic.

**Comment by andrewisen** [comment]
I noticed that my [multi-web-worker](https://github.com/andrewisen/IFC.js-web-worker-example/tree/master/examples/04/multi-web-worker) example didn't perform as well with the latest changes (e.g. https://github.com/agviegas/IFC.js/commit/b41d41b60188d255ef0da7b9470200060a148b14, https://github.com/agviegas/IFC.js/commit/453640866ed823c91913a35d75026e36d2257dd0, https://github.com/agviegas/IFC.js/commit/d92e8f87211f87d798c10b853f446c0ee900a579).

There is a time penalty for starting an additional Web Worker. My guess is that the parser is so much faster now that there's no performance gain to be made. This might be different for large (>200MB) IFC files.

I will experiment this some more 😄

**Comment by agviegas** [comment]
I'm closing this issue for now, as the main responsible for optimization now are both [web-ifc-three](https://github.com/tomvandig/web-ifc-three) and [web-ifc](https://github.com/tomvandig/web-ifc). Feel free to drop new ideas there to make this even faster!
