### ISSUE TITLE
Parser doesnt handle empty IFCTEXT marker

### ISSUE THREAD

**Issue by bpinel** [agviegas/IFC.js#4]
When loading file that contains line like :
#73 = IFCPROPERTYSINGLEVALUE('BO_links', 'Links', IFCTEXT(''), $);
parsing fails because IFCTEXT is empty. 
Have tried to find a fix but the way chevrotain.js is working is not easy to understand ! ;-)

**Comment by agviegas** [comment]
You are right, I have checked it and the current parser doesn't support empty texts when parsing `IfcValue` instances. I will fix this these days and, more importantly, I will expand the [CONTRIBUTING  document](https://github.com/agviegas/IFC.js/blob/master/CONTRIBUTING.md) document to explain in detail how each piece of the application works. 

In the meantime, you can find some sample [IFC files](https://github.com/agviegas/IFC.js/tree/master/resources/ifcs) I have uploaded to test the current implementation. 🙂

**Comment by bpinel** [comment]
Thanks for very much for your work. This is great and it was also on my mind to build an IFC loader on top of Three.js.
Also great to have some samples as mine are working yet. 
I will try to contribute if possible.

**Comment by agviegas** [comment]
I have corrected this issue in the parser. You can check it [here](https://github.com/agviegas/IFC.js/commit/474d79b0d9242f417e2337d535542ac2a8da1ec3). Also, I am updating the CONTRIBUTING doc to clarify the code. [Here](https://github.com/agviegas/IFC.js/blob/master/CONTRIBUTING.md#5-how-does-the-parser-works) you will find a first version of the documentation for the parser. This is a work in progress, and I am aware that this needs a whole documentation page, which will be developed in github pages in the future. Note that helping with the development of these docs is another way of contribution. 🙂 

For now, I have deployed the application [here](https://agviegas.github.io/IFC.js/) for easier testing. Even though I have corrected your issue, I still need to implement some additional ifc classes before you can load a full real project. Feel free to send me any IFC that are not loading yet so I can list the upcoming issues down.
