### ISSUE TITLE
Make Breps faster

### ISSUE THREAD

**Issue by agviegas** [agviegas/IFC.js#40]
I have benchmarked the speed of all the lading steps (breaking down the `buildGeometry` function):

![image](https://user-images.githubusercontent.com/56475338/107712092-14e96b00-6cc9-11eb-84cd-27e21ce6f089.png)

There are many places where the code can be improved, but one of the places I am most aware of is the generation of Breps. As you may know, breps are geometries defined by planes in space. The problem is that Three.js is only capable of constructing triangles in space, and the planes of Breps can have more than three points. So the [current implementation](https://github1s.com/agviegas/IFC.js/blob/HEAD/src/ifc-to-three.js/geometry-generator/three-geometry/three-brep.js) runs a rather expensive algorithm using quaternions. This algorithm is something I borrowed from [here](https://stackoverflow.com/questions/50272399/three-js-2d-object-in-3d-space-by-vertices/50274103#50274103). 

Nonetheless, there is a much more efficient way to create geometry without the need to use this algorithm: triangulating all the faces and [generating the geometry directly](https://threejsfundamentals.org/threejs/lessons/threejs-custom-buffergeometry.html). For this, we need to triangulate the points, which is a challenging task that, fortunately, has already been addressed by [others](https://github.com/mapbox/earcut).

I will play around these days with this idea.

BTW: I am not sure if we should generate the edges or bring this outside to the example. It slows things down an this is something the user can implement if they want.

**Comment by agviegas** [comment]
I have a first implementation of the algorithm, and I am very happy with the result.

![image](https://user-images.githubusercontent.com/56475338/107834988-39f8df00-6d98-11eb-8365-c10a9dfe4552.png)

This looks very similar to the geometry generated with the previous algorithm, but faster. To be precise, 5 times faster.

![image](https://user-images.githubusercontent.com/56475338/107835068-847a5b80-6d98-11eb-9917-e420278d25ac.png)

This speed improvement depend on the object, but if I load a scene full of breps, we can see that the gain is substantial:

![image](https://user-images.githubusercontent.com/56475338/107835172-dd49f400-6d98-11eb-9676-a0dd03e5dac8.png)

Obviously, the more breps, the more the gain. But this is not the most important part of this implementation. This algorithm is able to take an arbitrary array of faces (defined by points) and construct the geometry really fast. My idea is that this will substitute the rest of geometry generators, so in the end all IFC entities will be defined as an array of vertices and constructed using this. This will make the code for geometry generation much shorter, cleaner and faster. 

I still need to implement the interior holes for the faces.

**Comment by agviegas** [comment]
![image](https://user-images.githubusercontent.com/56475338/107835837-27cc7000-6d9b-11eb-80ce-3c8b2da1c76a.png)

Before: 
![before](https://user-images.githubusercontent.com/56475338/107835859-3581f580-6d9b-11eb-8860-4eeb78fdb28d.JPG)
Now:
![after](https://user-images.githubusercontent.com/56475338/107835903-6c580b80-6d9b-11eb-8624-ea40620629eb.JPG)

**Comment by vegarringdal** [comment]
looking good.

**Comment by agviegas** [comment]
I have pushed the changes with the first implementation of the algorithm. I will try to use this to generate all other geometries to make everything faster and cleaner.
