### ISSUE TITLE
Error loading IFC file: NoViableAltException on IfcPropertyEnumeratedValue construct

### ISSUE THREAD

**Issue by pablo-mayrgundter** [agviegas/IFC.js#43]
Loading a ~23MB file in the example file viewer, I get an error at this point in my file:

#1284= IFCPROPERTYENUMERATEDVALUE('Status',$,(IFCLABEL('EXISTING')),#1282);

pablo:~/IFC.js> git log -1
commit 0dbe637cf766aa8074b4fac39fd7373f2d535f5b (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Ansoni <antoniogviegas@hotmail.com>
Date:   Sun Feb 14 00:54:37 2021 +0100

    Refactor / clean up new brep algorithm

![image](https://user-images.githubusercontent.com/2480879/110037002-d2391280-7d0b-11eb-9d15-acbf0501c39f.png)

**Comment by agviegas** [comment]
Hey! Right now we are migrating everything to WASM. Wait for the next commits these days and let me know if you are still facing this issue.

**Comment by agviegas** [comment]
Hey @pablo-mayrgundter we have just updated the library. Can you give a try to the current implementation and let us know how it goes?

**Comment by pablo-mayrgundter** [comment]
Yep, loads and extremely quickly.  Impressive!  There are some new rendering bugs I haven't seen before.. are you still in process or should I file a different bug?

**Comment by agviegas** [comment]
Great to hear that! You should create an issue with this in [web-ifc](https://github.com/tomvandig/web-ifc), as this is the repository in charge of the geometry generation.
