### ISSUE TITLE
Could you add ifc sample?

### ISSUE THREAD

**Issue by mudin** [agviegas/IFC.js#5]
Hi @agviegas,
You have started the really awesome work!

uploading all the samples I have is currently failing.
Could you add the sample you successfully parser?
So that we can see the result.
It would be nice it loads directly from resources folder without user upload.

Thanks

**Comment by agviegas** [comment]
Thanks @mudin ! 

There might be several reasons why your IFC files are failing. If you look at the _console_ , you would probably get a clue of the issue. My guess is that your IFC files either have entities that I have not implemented yet, or they are IFC4 (for now, I am only implementing IFC2x3). 

 I have just uploaded some sample IFC files: f4e6fa62e33264a703afbac9d8c94a4c86e1e769 . Bear in mind that you can control the aspect of the elements from [here](src/ifc-to-three.js/scene/materials.js). 

On the other hand, I am constantly reloading the page while I develop, so I don't think that automatically loading an IFC file of the samples is very efficient, at least at this point. Nonetheless, you can implement that change simply ignoring the [loading button](src/ifc-file-reader.js) and hardcoding the route to the IFC you want to load by default on your end.

I am really looking forward to seeing more of your PRs. 🙂

**Comment by mudin** [comment]
Hi @agviegas,
Thank you for the files. It is already helpful.
It would be good to have todo list.
I hope to contribute more 🙂
Mudin

**Comment by agviegas** [comment]
I have decided to add branches with examples that are loaded on startup: see branch `example-01`. I will make this the deployed version for some days for the dissemination of the project, even though I still need to make the logic for clearing the scene.

**Comment by mudin** [comment]
@agviegas this is really good decision!
I was also thinking about this. But I was not sure if you like it or not :)

**Comment by mudin** [comment]
@agviegas Can I seperate core and UI? The problem here is all mixed. I would like to separate and build it as standalone library.
