### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by spookyfox** [agviegas/IFC.js#6]
![image](https://user-images.githubusercontent.com/14878872/100604225-876fbf00-3306-11eb-85b7-e38c8a1ff0fc.png)

I tried to load your example file `simple building.ifc` but the error above is raised?!

**Comment by agviegas** [comment]
Are you finding the same issue in the [deployed version](https://agviegas.github.io/IFC.js/)? Which browser are you using? Does this only happen with the `simple building.ifc` sample? Did you make any modifications to the IFC file?
